### ISSUE TITLE
GridBox ipywidget in WidgetControl is broken

### ISSUE THREAD

**Issue by kgiacobbi** [jupyter-widgets/ipyleaflet#356] opened 2019-05-06 13:59 UTC
Hi, i would like to add a GridBox to a WidgetControl but the GridBox is completly broken inside the WidgetControl.

```Python
from ipywidgets import GridBox, Layout, FloatRangeSlider, FloatText, Dropdown
from ipyleaflet import WidgetControl, Map

m = Map(zoom=1)

v1 = FloatText(layout = Layout(
                                width='auto', grid_area='v1'))

v2 = FloatText(layout = Layout(
                                width='auto', grid_area='v2'))

drop = Dropdown(layout = Layout(
                                width='auto', grid_area='drop'))

slider = FloatRangeSlider(layout = Layout(
                                width='auto', grid_area='slider'))


grid = GridBox(children=[v1,v2,drop, slider],
        layout=Layout(justify_content='center',
            width='500px',
            grid_template_rows='auto auto auto',
            grid_template_columns='80px 300px 80px',
            grid_template_areas='''
            "v1 . v2"
            ". slider ."
            " . drop ."

            ''')
       )
display(grid)

m.add_control(WidgetControl(widget=grid))

display(m)
```

**Comment by kgiacobbi** [comment] 2019-05-07 07:57
My GridBox in Jupyter lab:
![widget](https://user-images.githubusercontent.com/49714549/57282982-6c978300-70ae-11e9-9dbe-f2938590a9c4.png)

My GridBox in WidgetControl:
![widget_map](https://user-images.githubusercontent.com/49714549/57283027-86d16100-70ae-11e9-85c2-876ddfddbf46.png)

**Comment by martinRenou** [comment] 2019-05-07 08:25
I quickly took a look at it but could not find what the issue is. I suppose it is a CSS issue, there must be a CSS attribute missing in the widgetcontrol container. 
I don't really have time to look at it, if you would like to take a shot at fixing it that would be great!

**Comment by kgiacobbi** [comment] 2019-05-16 11:55
Hi,
I tried to look at the problem, but i can't found how to fix it.
If someone can try...
Because, for my internship, the widget has to be display well on the map. And for now, it's not.
Thanks

**Comment by martinRenou** [comment] 2019-05-16 12:39
Looking at your issue, I see a big difference between the content of the two grids. It looks like the style is not added:
Text box contained by the grid **outside** of the WidgetControl:
```html
<div class="p-Widget jupyter-widgets widget-inline-hbox widget-text" 
     style="width: auto; grid-area: v1 / v1 / v1 / v1;">...</div>
```
Text box contained by the grid **inside** of the WidgetControl:
```html
<div class="p-Widget jupyter-widgets widget-inline-hbox widget-text">...</div>
```

I start to feel like it is an ipywidgets bug. I guess we need to dig a bit in the ipywidgets code base in order to see where this `grid-area` parameter is added.

**Comment by martinRenou** [comment] 2019-05-17 07:17
@kgiacobbi this PR #364 should fix your issue. I think it is a temporary fix until we find a better one.

**Comment by martinRenou** [comment] 2019-06-20 09:52
This is not fixed yet, we should keep this issue opened

**Comment by SylvainCorlay** [comment] 2019-06-25 13:21
@kgiacobbi this is fixed in master. We are making a release with that fix now!

**Closed by SylvainCorlay** 2019-06-25 13:21 UTC
