### ISSUE TITLE
TileLayer visible parameter not working

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#519] opened 2020-03-16 20:05 UTC
When a TileLayer's `visible` attribute to set to `False`, the layer can not be controlled using the LayerControl. Even when the layer name is `checked` under the LayerControl, the layer won't show up.  If the `visible` attribute is set to `True`, it can be turned on/off properly using the LayerControl. 

```
from ipyleaflet import *
m = ipyleaflet.Map(center=(40, -100), zoom=4)
m.add_control(LayersControl(position='topright'))

layer = TileLayer(
            url='https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
            name='Google Map',
            attribution='Google',
            visible=False   
        )
m.add_layer(layer)

m
```

**Comment by davidbrochart** [comment] 2020-03-16 21:58
Yes, if the `visible` attribute of the layer is `False`, then toggling the layer on or off in the `LayersControl` won't have any effect, because it will either not show the layer (off) or show a layer that is not visible (on). The thing is that the check button in the front-end is not linked to the `visible` attribute, they are two separate things.

**Comment by martinRenou** [comment] 2020-03-17 14:25
There was some work done here: https://github.com/jupyter-widgets/ipyleaflet/pull/435. But I remember it not working really well.

I agree the LayersControl should update the `visible` attribute of the layers. It's not was the PR is doing, but we might want to give up on this PR and go with the `visible` attribute approach.

**Comment by martinRenou** [comment] 2021-03-03 13:06
Closing as duplicate of https://github.com/jupyter-widgets/ipyleaflet/issues/452

**Closed by martinRenou** 2021-03-03 13:06 UTC
