### ISSUE TITLE
v0.17.0 does not work with Colab

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#1018] opened 2022-07-08 15:19 UTC
v0.16.0 works fine with Google Colab. However, v0.17.0 no longer works with Colab. The map does not show up. 
Relevant issues:

-  https://github.com/giswqs/geemap/issues/1132 
- https://github.com/googlecolab/colab-cdn-widget-manager/issues/25

**Comment by davidbrochart** [comment] 2022-07-08 15:38
Maybe caused by #988 @jasongrout ?

**Comment by jasongrout** [comment] 2022-07-08 17:37
Yes, it looks like an interaction between #988 (which depends on a feature of requirejs) and colab not using requirejs to load the AMD module. I'm following up at https://github.com/googlecolab/colab-cdn-widget-manager/issues/25, so I'll close this issue in favor of that conversation.

**Closed by jasongrout** 2022-07-08 17:37 UTC
