### ISSUE TITLE
GeoJSON does not render in saved HTML

### ISSUE THREAD

**Issue by KennethWussmann** [jupyter-widgets/ipyleaflet#896] opened 2021-12-01 20:29 UTC
Hey!
I'm having issues rendering GeoJSON on a map and saving that map to HTML.
This is the [example from the docs](https://ipyleaflet.readthedocs.io/en/latest/api_reference/geo_json.html) I'm using:

```python
import os
import json
import random
import requests

from ipyleaflet import Map, GeoJSON

if not os.path.exists('europe_110.geo.json'):
    url = 'https://github.com/jupyter-widgets/ipyleaflet/raw/master/examples/europe_110.geo.json'
    r = requests.get(url)
    with open('europe_110.geo.json', 'w') as f:
        f.write(r.content.decode("utf-8"))

with open('europe_110.geo.json', 'r') as f:
    data = json.load(f)

def random_color(feature):
    return {
        'color': 'black',
        'fillColor': random.choice(['red', 'yellow', 'green', 'orange']),
    }

m = Map(center=(50.6252978589571, 0.34580993652344), zoom=3)

geo_json = GeoJSON(
    data=data,
    style={
        'opacity': 1, 'dashArray': '9', 'fillOpacity': 0.1, 'weight': 1
    },
    hover_style={
        'color': 'white', 'dashArray': '0', 'fillOpacity': 0.5
    },
    style_callback=random_color
)
m.add_layer(geo_json)

# The only thing I added, save it to HTML:
m.save("europe.html")
```

Once saved and opened the map stays empty. This is probably because the HTML wants to load some `undefined` third party library:

![Screenshot 2021-12-01 at 21 24 02](https://user-images.githubusercontent.com/11491506/144308345-795b8328-7c2e-44c1-b12f-cf09e5f311a4.png)

You can find the entire [HTML file here](https://gist.github.com/KennethWussmann/b2ecf396780702b723303bebb5a0eaee#file-europe-html).

What library is it trying to load? 

Thank you!

### Versions
```
ipyleaflet = "0.14.0"
python = "3.10"
jupyter = "1.0.0"
ipykernel = "6.5.1"
requests = "2.26.0"
```

**Comment by martinRenou** [comment] 2022-04-08 11:50
Duplicate of #810

**Closed by martinRenou** 2022-04-08 11:50 UTC
