### ISSUE TITLE
Get access to layer/control visibility in Python?

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipyleaflet#797] opened 2021-03-03 12:58 UTC
I wonder if it's possible to tell with Python code if a layer is visible or not at any given time, say after checking or unchecking it in the `LayersControl`? If it exists I haven't discovered it, yet. (The same holds for controls, which I haven't tested, yet.)

**Comment by martinRenou** [comment] 2021-03-03 13:05
duplicate of https://github.com/jupyter-widgets/ipyleaflet/issues/452

**Closed by martinRenou** 2021-03-03 13:05 UTC
