### ISSUE TITLE
SplitMap control does not work in saved HTML

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#897] opened 2021-12-02 13:45 UTC
When exporting a map with a SplitMap control to an HMTL file, the SplitMap control won't show up. 
Related issue: https://github.com/giswqs/streamlit-geospatial/issues/11

```python
from ipyleaflet import Map, basemaps, basemap_to_tiles, SplitMapControl

m = Map(center=(42.6824, 365.581), zoom=5)

right_layer = basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-11-11")
left_layer = basemap_to_tiles(basemaps.NASAGIBS.ModisAquaBands721CR, "2017-11-11")

control = SplitMapControl(left_layer=left_layer, right_layer=right_layer)
m.add_control(control)
m.save("map.html")
m
```
In Jupyter:
![image](https://user-images.githubusercontent.com/5016453/144432955-a4c8abd8-612c-4190-b0a8-bafe2a1243a8.png)

In saved HTML:
![image](https://user-images.githubusercontent.com/5016453/144433067-8f66604e-38f1-41f6-ad57-eee30869bd3f.png)

![image](https://user-images.githubusercontent.com/5016453/144433703-3f7d6d2c-2e0f-47fd-a70a-c5344deab4de.png)

**Comment by tianranZH** [comment] 2022-01-28 12:06
I also hit this issue in a fire mapping project, the splitmap is not showing in the saved html, only basemap there
[fire_overlay_burned_area_sentinel2.zip](https://github.com/jupyter-widgets/ipyleaflet/files/7958448/fire_overlay_burned_area_sentinel2.zip)

**Comment by martinRenou** [comment] 2022-04-08 11:50
Duplicate of https://github.com/jupyter-widgets/ipyleaflet/issues/810

**Closed by martinRenou** 2022-04-08 11:50 UTC
