### ISSUE TITLE
Failed to display Jupyter Widget of type Map

### ISSUE THREAD

**Issue by eRajsh** [jupyter-widgets/ipyleaflet#173] opened 2018-05-30 04:58 UTC
Had created an issue under JupyterLab repo (https://github.com/jupyterlab/jupyterlab/issues/4654). Maybe this is the right place.

Recently installed Anaconda 3.5.1 on mac, and trying to write a simple map thingy in the notebook.

Ran the commands (pip install ipyleaflet) successfully

Extensions seem to be properly installed:
![](https://user-images.githubusercontent.com/1895122/40637836-33059402-6325-11e8-9190-4a9c706a0c74.png)

Here is the code in the notebook:
***************************************************************
!jupyter nbextension enable --py widgetsnbextension --sys-prefix
!jupyter nbextension enable --py --sys-prefix ipyleaflet

import pandas as pd
from ipyleaflet import Map

Map(center=[ 37.7749, -112.4194], zoom = 10)
***************************************************************

When I run the notebook, I get the following issue:
Enabling notebook extension jupyter-js-widgets/extension...
- Validating: OK
Enabling notebook extension jupyter-leaflet/extension...
- Validating: OK
Failed to display Jupyter Widget of type Map.

**Comment by clemens-tolboom** [comment] 2018-06-12 15:58
I get the same report but succesfull map

```bash
> jupyter nbextension list
Known nbextensions:
  config dir: /Users/.../bin/../etc/jupyter/nbconfig
    notebook section
      jupyter-leaflet/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

Not sure this is useful but pasting the code into a notebook

```python
import pandas as pd
from ipyleaflet import Map

Map(center=[ 37.7749, -112.4194], zoom = 10)
```
produces a map.

I'm on MacOs using `pipenv`

**Comment by eRajsh** [comment] 2018-06-14 04:09
Thx Clemens-tolboom for trying it out. I cannot resolve the issue, tried reinstalling from scratch, still the same. I am also on Mac.

**Comment by SylvainCorlay** [comment] 2018-06-14 06:40
@eRajsh do you see errors in the js console (option/command/j to open the developer tools on mac).

**Comment by SylvainCorlay** [comment] 2018-06-14 06:41
Also, can you please provide the full output of `jupyter nbextension list`?

**Comment by costrouc** [comment] 2018-06-26 21:37
I have the exact same issue. I created a new virtualenv to test. Here are the exact steps that I took on Ubuntu 18.04. 

```bash
pipenv install ipyleaflet jupyterlab
pipenv run jupyter labextension install jupyter-leaflet
pipenv run jupyter lab
```

Inside of the launched notebook. I ran the [Map](https://ipyleaflet.readthedocs.io/en/latest/api_reference/map.html)  example and this was the result.

```python
from ipyleaflet import Map, basemaps, basemap_to_tiles

m = Map(
    layers=(basemap_to_tiles(basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-04-08"), ),
    center=(52.204793, 360.121558),
    zoom=4
)

m
```

`Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map …`

I checked nbextension and this was the result

```shell
$ pipenv run jupyter nbextension list
Known nbextensions:
  config dir: /home/costrouc/.virtualenvs/testleaf-79UVUn5m/etc/jupyter/nbconfig
    notebook section
      jupyter-leaflet/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

```shell
$ pipenv run pip list

Package             Version
------------------- -------
backcall            0.1.0  
bleach              2.1.3  
decorator           4.3.0  
entrypoints         0.2.3  
html5lib            1.0.1  
ipykernel           4.8.2  
ipyleaflet          0.8.4  
ipython             6.4.0  
ipython-genutils    0.2.0  
ipywidgets          7.2.1  
jedi                0.12.0 
Jinja2              2.10   
jsonschema          2.6.0  
jupyter-client      5.2.3  
jupyter-core        4.4.0  
jupyterlab          0.32.1 
jupyterlab-launcher 0.10.5 
MarkupSafe          1.0    
mistune             0.8.3  
nbconvert           5.3.1  
nbformat            4.4.0  
notebook            5.5.0  
numpy               1.14.5 
pandas              0.23.1 
pandocfilters       1.4.2  
parso               0.2.1  
pexpect             4.6.0  
pickleshare         0.7.4  
pip                 10.0.1 
prompt-toolkit      1.0.15 
ptyprocess          0.6.0  
Pygments            2.2.0  
python-dateutil     2.7.3  
pytz                2018.4 
pyzmq               17.0.0 
Send2Trash          1.5.0  
setuptools          39.2.0 
simplegeneric       0.8.1  
six                 1.11.0 
terminado           0.8.1  
testpath            0.3.1  
tornado             5.0.2  
traitlets           4.3.2  
traittypes          0.2.1  
wcwidth             0.1.7  
webencodings        0.5.1  
wheel               0.31.1 
widgetsnbextension  3.2.1  
xarray              0.10.7 
```

**Comment by costrouc** [comment] 2018-06-27 03:11
I found the issue. I will submit a pull request to update the docs and make the binder instance work with jupyter lab (it currently does not). I have found that running the following works.

```shell
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-leaflet
```

The step that I missed was the `jupyter-widgets/jupyterlab-manager` extension.

See #168 where the issue is related.

**Comment by SylvainCorlay** [comment] 2018-06-27 03:58
OK, did not read this with enough attention earlier.

The `nbextension`s only concern the classic notebook. To enable widgets and ipyleaflet with JupyterLab, you need to install the lab extensions

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-leaflet
```

**Comment by SylvainCorlay** [comment] 2018-06-27 03:58
Closing as solved, although feel free to comment should you other issue.

**Closed by SylvainCorlay** 2018-06-27 03:58 UTC

**Comment by clemens-tolboom** [comment] 2018-06-27 07:32
I should have read more careful as this is about Jupyter __Lab__ :-[ I'm using plain old Jupyter.

**Comment by hexagonrecursion** [comment] 2020-01-25 19:47
1. Is there any reason why this has to be done manually? Why can't `conda install` be enough?
2. If the additional steps absolutely have to be performed manually they must be documented here https://jupyter.org/widgets (currently they are not)

**Comment by martinRenou** [comment] 2020-01-27 07:30
> Is there any reason why this has to be done manually? Why can't conda install be enough?

JupyterLab needs to be **entirely** rebuilt with jupyter-leaflet included in it. That is why it is a separate command.

> If the additional steps absolutely have to be performed manually they must be documented here https://jupyter.org/widgets (currently they are not)

You are right. I will open a PR on the website for that fix
