### ISSUE TITLE
Some parameters in Geo_Json of Callback of DrawControl do not change after editing

### ISSUE THREAD

**Issue by ONLYA** [jupyter-widgets/ipyleaflet#305] opened 2019-03-09 00:11 UTC
I wrote a  callback function to print the geo_json on drawing a circle. It works perfectly when the circle is created. However, the issue starts when I edit the circle.
* coordinate of the circle in geo_json can be changed
* radius of the circle in geo_son cannot be changed
![image](https://user-images.githubusercontent.com/36487580/54062714-be7f7200-41ff-11e9-8b2e-f1df54b4817c.png)
![image](https://user-images.githubusercontent.com/36487580/54062731-db1baa00-41ff-11e9-9709-134588e632d3.png)
![image](https://user-images.githubusercontent.com/36487580/54062740-e40c7b80-41ff-11e9-810b-1d0aff840a80.png)

**Comment by martinRenou** [comment] 2019-03-11 07:28
Thanks for the report. There is an issue with the edit button: #218. The issue is still not fixed. We need more contributors! If you would like to try and fix it that would be great :)

**Comment by martinRenou** [comment] 2019-05-03 06:03
Fixed by #344

**Closed by martinRenou** 2019-05-03 06:03 UTC
