### ISSUE TITLE
Marker title attribute has no effect

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipyleaflet#875] opened 2021-10-03 14:24 UTC
The documentation says that `Marker` has the `title` attribute for setting the tooltip, but it has no effect. Hoving over the marker does not show the tooltip. 

https://ipyleaflet.readthedocs.io/en/latest/api_reference/marker.html
![image](https://user-images.githubusercontent.com/5016453/135757382-74b3cb94-fee0-4bd7-ad1a-4ed5329a5bf8.png)

```
from ipyleaflet import Map, Marker

center = (52.204793, 360.121558)

m = Map(center=center, zoom=15)

marker = Marker(location=center, draggable=False)
marker.title = "This is tooltip"
m.add_layer(marker);

m
```

**Comment by sackh** [comment] 2021-10-04 05:29
duplicate of - https://github.com/jupyter-widgets/ipyleaflet/issues/676 ?

**Comment by giswqs** [comment] 2021-10-04 20:11
I was looking for an ipyleaflet feature similar to the folium Marker tooltip attribute as shown below. I am not sure if it is feasible. 

App: https://share.streamlit.io/dansbecker/weather-analytics/main
Code: https://github.com/dansbecker/weather-analytics/blob/main/streamlit_app.py#L125

```
        folium.CircleMarker(location=[city.lat, city.lon],
                    tooltip=f"{city.municipality}\n  value: {city[field_to_color_by]}{metric_unit}",
                    fill=True,
                    fill_color=icon_color,
                    color=None,
                    fill_opacity=0.7,
                    radius=5,
                    popup = folium.Popup().add_child(
                                            folium.features.VegaLite(city_graph)
                                            )
                    ).add_to(main_map)
```
![](https://i.imgur.com/riV9Llr.gif)

**Closed** 2023-06-05 16:35 UTC

**Comment by schoulten** [comment] 2024-10-23 19:26
Hey @giswqs, have you find a solution in ipyleaflet that works similar to folium Marker tooltip?

**Comment by giswqs** [comment] 2024-10-23 19:30
@schoulten Yes, I did. 

See this example: https://github.com/opengeos/HyperCoast/blob/main/hypercoast/common.py#L1037

![](https://i.imgur.com/Q8pBQXg.png)
