### ISSUE TITLE
basemaps.Hydda and Strava maps grey in documentation

### ISSUE THREAD

**Issue by Geo4Dev** [jupyter-widgets/ipyleaflet#848] opened 2021-06-24 16:55 UTC
The maps using basemaps.Hydda and basemaps.Strava are all grey in the basemaps documentation: https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html

**Comment by StefanBrand** [comment] 2021-06-29 12:02
Duplicate of #614?

**Comment by HaudinFlorence** [comment] 2022-08-17 14:33
The Hydda basemap has been removed from the examples https://github.com/jupyter-widgets/ipyleaflet/pull/966

**Closed** 2022-08-17 14:41 UTC
