### ISSUE TITLE
Hydra full s completely grey

### ISSUE THREAD

**Issue by ClaudeMa** [jupyter-widgets/ipyleaflet#829] opened 2021-05-27 10:42 UTC
On https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html
Map(basemap=basemaps.Hydda.Full, center=center, zoom=zoom) s completely grey

**Comment by davidbrochart** [comment] 2021-05-27 12:22
Duplicate of #614

**Closed by davidbrochart** 2021-05-27 12:22 UTC
