### ISSUE TITLE
How to detect a selection from the LayerControl

### ISSUE THREAD

**Issue by galewis2** [jupyter-widgets/ipyleaflet#565] opened 2020-04-28 18:36 UTC
I'm looking to fire another event after action in LayerControl. I have the classic example:

```
[snip]
import ipywidgets

def o_handler(**kwargs):
    coordinates.value = str(kwargs.get('coordinates'))

    
coordinates = ipywidgets.Label(value='[]')
control = ipyleaflet.LayersControl(position='topright')

map_osm.on_interaction(o_handler)
[/snip]
```

However I'd like to change the coordinates.value if a different layer becomes visible

Any help would be greatly appreciated.

**Comment by martinRenou** [comment] 2020-04-29 07:06
Related to #452.

It is not currently possible unfortunately. There is a PR opened for adding this kind of behavior to the LayersControl but it is not yet decided: https://github.com/jupyter-widgets/ipyleaflet/pull/435

**Comment by martinRenou** [comment] 2021-03-03 13:05
Closing as duplicate of https://github.com/jupyter-widgets/ipyleaflet/issues/452

**Closed by martinRenou** 2021-03-03 13:05 UTC
