### ISSUE TITLE
map not visible

### ISSUE THREAD

**Issue by maessery** [jupyter-widgets/ipyleaflet#865] opened 2021-09-02 15:08 UTC
hi, i was looking at your work on https://ipyleaflet.readthedocs.io/en/latest/api_reference/basemaps.html#
 with basemaps, specifically, and noticed all your Strava maps were greyed out. There was a note box that suggested reaching out on  here if that situation occured on the site.

As a side note, im interested to see what it produces! Is it a way of plotting streets and drivable routes?

**Comment by davidbrochart** [comment] 2021-09-02 15:16
Hi, we depend on `xyzservices`, and it seems [the Strava server is currently down](https://github.com/geopandas/xyzservices/blob/f6f5e8640596721400af5c2bdbefe2fc150dae72/CHANGELOG.md#xyzservices-2021081-august-12-2021).

**Comment by justb4** [comment] 2021-09-09 15:23
From what I see the problem is just a typo double slash, '//tiles/' in the Strava URLs on [basemaps.py#199 and further](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py#L199):

```
    Strava=Bunch(
        All=dict(
            url='https://heatmap-external-a.strava.com//tiles/all/hot/{z}/{x}/{y}.png?v=19',
            max_zoom=15,
            attribution='Map tiles by <a href="https://labs.strava.com/heatmap">Strava 2017</a>',
            name='Strava.All'
        ),
 .
.

```
So https://heatmap-external-a.strava.com/tiles/all/hot/10/163/393.png will render but 
https://heatmap-external-a.strava.com//tiles/all/hot/10/163/393.png not.

**Comment by justb4** [comment] 2021-09-09 15:32
And https://github.com/geopandas/xyzservices/pull/85 (the more `xyzservices` becomes relevant!).

**Comment by martinRenou** [comment] 2021-09-09 15:40
Thanks for reporting. So it might only be a matter of updating the docs. We maybe need to update the stable branch.

**Comment by martinRenou** [comment] 2021-09-09 15:40
Thanks for reporting. So it might only be a matter of updating the docs. We maybe need to update the stable branch.

**Comment by martinRenou** [comment] 2021-09-09 15:41
Rebuilding now

**Comment by justb4** [comment] 2021-09-09 15:50
Not too familiar how xyzservices is used, thought it was WIP via PR #857.
To me it seems that only
https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py#L199 needs updating...

**Comment by martinRenou** [comment] 2021-09-09 17:22
Indeed. I thought the xyzservices PR was merged and released, but it is still open https://github.com/jupyter-widgets/ipyleaflet/pull/857.

So yeah we need to finish this.

**Comment by justb4** [comment] 2021-09-12 10:20
I can make a PR to update https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py#L199.

**Comment by martinRenou** [comment] 2021-09-13 07:59
thanks!

**Closed by martinRenou** 2021-09-13 07:59 UTC
