### ISSUE TITLE
ipyleaflet is broken (missing file on CDN)

### ISSUE THREAD

**Issue by naschmitz** [jupyter-widgets/ipyleaflet#1192] opened 2024-04-30 19:03 UTC
The jupyter-leaflet@0.19 implementation no longer exists on the jsdelivr CDN. I get a 404 when loading https://cdn.jsdelivr.net/npm/jupyter-leaflet@0.19/dist/index.js. ipyleaflet was working fine yesterday, and today it's not.

**Comment by giswqs** [comment] 2024-04-30 19:19
@martinRenou @maartenbreddels it seems the newest ipyleaflet v0.19.0 is broken. It doesn't work on Colab

**Comment by maartenbreddels** [comment] 2024-05-02 19:29
@iisakkirotko do you want to take a look at this?

**Comment by maartenbreddels** [comment] 2024-05-14 08:02
The issue was fixed in https://github.com/jupyter-widgets/ipyleaflet/commit/fd02487e1402de6f947b58d79720ebda27cf593d, and I released version 0.19.1, which contains this fix.

Due to the loose dependency in ipyleaflet (using semver ^0.19.0), voila will pick up 0.19.1 from the CDN, so you might not need to upgrade.

**Comment by giswqs** [comment] 2024-05-14 12:37
Thank you very much for fixing it. I can confirm that now ipyleaflet works properly on Colab

**Comment by martinRenou** [comment] 2024-05-14 12:38
Thanks a lot @maartenbreddels !

**Closed** 2024-05-14 12:38 UTC
